[window]
padding.x = 1
padding.y = 1
dimensions.columns = 80
dimensions.lines = 45
decorations = "Buttonless"
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Windowed"

[font]
normal.family = "0xProto Nerd Font"

size = 12
